# Supabase configuration for production deployment
# Local development settings removed - using live Supabase instance only

project_id = "yoga-swiss"

[api]
# Production API configuration
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
# Production database configuration
major_version = 17

[db.pooler]
# Production connection pooling
pool_mode = "transaction"
default_pool_size = 15
max_client_conn = 100

[studio]
# Production Studio configuration
# Note: Using live Supabase Studio at https://supabase.com/dashboard

[storage]
# Production storage limits
file_size_limit = "50MiB"

[auth]
# Production auth configuration
# Note: Using live Supabase auth configuration
enable_signup = true
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = false
